### ISSUE TITLE
Add identifiers to UI Components for WDIO

### ISSUE THREAD

**Issue by olgapuig** [systelab/systelab-components#707]
**Is your feature request related to a problem? Please describe.**
Some UI Components are located by ClassName instead of having identifier. 

**Describe the solution you'd like**
This task consists of reviewing the [widgets ](https://github.com/systelab/systelab-components-wdio-test/tree/main/src/widgets) and add identifiers in the template (HTML) to ensure the proper access.
Then, the [WDIO wrapper ](https://github.com/systelab/systelab-components-wdio-test) can be updated to locate by id

**Comment by fjaguado** [comment]
In Beacon we are using a e2e directive to add a data-e2e attribute for testing purpose. Why? Because the usage of IDs for testing is not a good practice and the data-e2e can me removed from templates as a parse step for production.

**Comment by jserra91** [comment]
In GWP we are using **data-testid** (https://www.w3schools.com/tags/att_data-.asp). The reason is that we have a lot of reusable components and to lighten the load and not have to redo testing code, we create code blocks to test the component directly. So we can reuse it in other screens and not only accessing the atoms components.

**Comment by fjaguado** [comment]
The work has been done in #732
